/*
 * Copyright 2026 Ronny Trommer <ronny@no42.org>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package auth

import (
	"context"
	"errors"
)

// ─── Provider-layer error sentinels ────────────────────────────────────────
//
// Wrapped by providers and unwrapped by the callback handler. Each maps to a
// specific 4xx response + audit row per § 4.5 of the change.
var (
	// ErrUnverifiedEmail — the provider returned an email that is not
	// verified (GitHub: primary && verified). Maps to 401 EMAIL_NOT_VERIFIED.
	ErrUnverifiedEmail = errors.New("oauth: email is not verified")
	// ErrNoEmail — the provider returned no email at all (e.g. Microsoft
	// tenants that omit the email claim). Maps to 401 EMAIL_NOT_VERIFIED.
	ErrNoEmail = errors.New("oauth: no email returned by provider")
	// ErrNotOrgMember — GitHub user is not a member of the allowed
	// organisation, or Microsoft tid claim does not match the configured
	// tenant. Maps to 403 ORG_MEMBERSHIP_REQUIRED.
	ErrNotOrgMember = errors.New("oauth: not a member of the allowed organisation/tenant")
	// ErrTokenExchange — the provider's token endpoint rejected the code
	// (expired, replayed, network error). Maps to 401 OAUTH_EXCHANGE_FAILED.
	ErrTokenExchange = errors.New("oauth: token exchange failed")
)

// Provider names — string constants matching the operators.first_seen_provider
// CHECK constraint and the URL `/api/v1/auth/login/{provider}` parameter.
const (
	ProviderGitHub    = "github"
	ProviderMicrosoft = "microsoft"
)

// OAuthIdentity is the contract the OAuth callback receives from a provider
// implementation. Email is the verified primary email, lowercased. OrgMember
// is true when the provider has confirmed organisation/tenant membership
// (GitHub: no42-org; Microsoft: configured tenant id) per D7's two-lock
// requirement. ProviderUserID is the provider-specific identifier (GitHub
// username or Microsoft UPN) and is stored opportunistically on the
// operators row for display purposes per D14.
type OAuthIdentity struct {
	Email          string
	OrgMember      bool
	ProviderUserID string
	Provider       string
}

// OAuthProvider is the boundary the OAuth login flow uses to talk to GitHub
// and Microsoft. Concrete implementations live in
// `auth/internal/auth/github` and `auth/internal/auth/microsoft`. Tests
// substitute fakes — there is no real network access in the test suite per
// the decision recorded in tasks.md.
type OAuthProvider interface {
	// Name returns the lowercase provider identifier ("github" or
	// "microsoft"). Used to key the route, the audit details, and the
	// state-store entry.
	Name() string
	// AuthorizeURL returns the URL the browser should be redirected to in
	// order to initiate the consent flow. state and codeChallenge are
	// generated by the login handler and stored under a transient handle;
	// the callback verifies them after the provider redirects back.
	AuthorizeURL(state, codeChallenge string) string
	// Exchange trades an authorisation code (and the matching PKCE verifier)
	// for an OAuthIdentity. The implementation is responsible for:
	//   - Token exchange against the provider's token endpoint
	//   - Verifying any tenant/org membership claim
	//   - Returning the canonicalised primary email
	// Errors should be wrapped with sentinels from this package so the
	// callback can map them to structured 4xx responses + audit rows.
	Exchange(ctx context.Context, code, codeVerifier string) (*OAuthIdentity, error)
}
